[2024-01-27T22:25:37.945+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_1.to_sqlite manual__2024-01-27T22:25:26.036149+00:00 [queued]>
[2024-01-27T22:25:37.950+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_1.to_sqlite manual__2024-01-27T22:25:26.036149+00:00 [queued]>
[2024-01-27T22:25:37.950+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-01-27T22:25:37.986+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): to_sqlite> on 2024-01-27 22:25:26.036149+00:00
[2024-01-27T22:25:37.990+0000] {standard_task_runner.py:57} INFO - Started process 46131 to run task
[2024-01-27T22:25:37.993+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_1', 'to_sqlite', 'manual__2024-01-27T22:25:26.036149+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/ETL_1.py', '--cfg-path', '/tmp/tmp1kdmz3sl']
[2024-01-27T22:25:37.994+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask to_sqlite
[2024-01-27T22:25:38.042+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_1.to_sqlite manual__2024-01-27T22:25:26.036149+00:00 [running]> on host codespaces-ca3784
[2024-01-27T22:25:38.155+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL_1' AIRFLOW_CTX_TASK_ID='to_sqlite' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T22:25:26.036149+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-27T22:25:26.036149+00:00'
[2024-01-27T22:25:38.156+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-27T22:25:38.157+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e "CREATE TABLE IF NOT EXISTS monthly_info (Date DATETIME, Monthly Max FLOAT, Monthly Low FLOAT, Mean Volume per Day FLOAT);\n.separator ","\n.import /workspaces/hands-on-introduction-data-engineering-4395021/lab/monthly_info.csv monthly_info" | sqlite3 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-load-db.db']
[2024-01-27T22:25:38.169+0000] {subprocess.py:86} INFO - Output:
[2024-01-27T22:25:38.174+0000] {subprocess.py:93} INFO - Parse error near line 1: duplicate column name: Monthly
[2024-01-27T22:25:38.225+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-27T22:25:38.230+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-27T22:25:38.232+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=ETL_1, task_id=to_sqlite, execution_date=20240127T222526, start_date=20240127T222537, end_date=20240127T222538
[2024-01-27T22:25:38.268+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 43 for task to_sqlite (Bash command failed. The command returned a non-zero exit code 1.; 46131)
[2024-01-27T22:25:38.285+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-01-27T22:25:38.294+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
