[2024-01-27T20:37:56.326+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_1.to_sqlite manual__2024-01-27T20:37:46.581992+00:00 [queued]>
[2024-01-27T20:37:56.332+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_1.to_sqlite manual__2024-01-27T20:37:46.581992+00:00 [queued]>
[2024-01-27T20:37:56.332+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-01-27T20:37:56.368+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): to_sqlite> on 2024-01-27 20:37:46.581992+00:00
[2024-01-27T20:37:56.372+0000] {standard_task_runner.py:57} INFO - Started process 5264 to run task
[2024-01-27T20:37:56.376+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_1', 'to_sqlite', 'manual__2024-01-27T20:37:46.581992+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ETL_1.py', '--cfg-path', '/tmp/tmp5z8f905b']
[2024-01-27T20:37:56.376+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask to_sqlite
[2024-01-27T20:37:56.427+0000] {task_command.py:410} INFO - Running <TaskInstance: ETL_1.to_sqlite manual__2024-01-27T20:37:46.581992+00:00 [running]> on host codespaces-ca3784
[2024-01-27T20:37:56.518+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL_1' AIRFLOW_CTX_TASK_ID='to_sqlite' AIRFLOW_CTX_EXECUTION_DATE='2024-01-27T20:37:46.581992+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-27T20:37:46.581992+00:00'
[2024-01-27T20:37:56.519+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-27T20:37:56.520+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ",separator ","\n. import --skip 1 /workspaces/hands-on-introduction-data-engineering-4395021/lab/monthly_info.csv monthly_info" | sqlite3 /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-load-db.db']
[2024-01-27T20:37:56.528+0000] {subprocess.py:86} INFO - Output:
[2024-01-27T20:37:56.829+0000] {subprocess.py:93} INFO - Parse error near line 1: near ",": syntax error
[2024-01-27T20:37:56.829+0000] {subprocess.py:93} INFO -   ,separator , . import --skip 1 /workspaces/hands-on-introduction-data-engineer
[2024-01-27T20:37:56.829+0000] {subprocess.py:93} INFO -   ^--- error here
[2024-01-27T20:37:56.830+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-01-27T20:37:56.836+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-01-27T20:37:56.840+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=ETL_1, task_id=to_sqlite, execution_date=20240127T203746, start_date=20240127T203756, end_date=20240127T203756
[2024-01-27T20:37:56.875+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task to_sqlite (Bash command failed. The command returned a non-zero exit code 1.; 5264)
[2024-01-27T20:37:56.908+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-01-27T20:37:56.917+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
